services:
  - type: web
    name: ocr-llm-fastapi
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn scan:app --host 0.0.0.0 --port 10000"
    envVars:
      - key: GROQ_API_KEY
        sync: false
    autoDeploy: true
    
# Notes:
# - Set your GROQ_API_KEY in the Render dashboard under Environment Variables.
# - The service will be available on port 10000.
# - Make sure requirements.txt is present in your repo. 